### PR TITLE
Added option to change the path

### PR DESCRIPTION
**Pull request by cfpwastaken**
With this PR you can change the path using -p or --path ex: `rpipress-downloader -p downloaded`

### CODE REVIEW

**Comment by artivis** [comment]
Hi @cfpwastaken,
Thanks for the PR. I'm afraid this feature won't work with the [snap version](https://snapcraft.io/rpipress-downloader) of this script. Snaps are confined and this particular one does not have access to e.g. the user's home. Plus, it would be proper to handle any error that may arrise in case the user provides a path without proper permissions (e.g. `rpipress-downloader -p /opt/downloaded`)
How do you use this 'dowloader', directly from the script or as a snap?

**Comment by cfpwastaken** [comment]
I use it directly on the script. I don't really know how snap works and stuff. And yes i prob should have added a test for permissions. But i think python will just throw its error so its fine?

**Comment by artivis** [comment]
Ok, then could you change the logic a bit so that this feature is only available if the script is not used as a snap? E.g. here when `os.getenv('SNAP_USER_DATA')` is none.
As for the error handling, I have no idea what [`urlreq.urlretrieve`](https://github.com/artivis/rpipress-downloader/blob/master/scripts/rpipress-downloader#L136) may throw, it may not be clear to the end-user so I'd prefer a small early check with a clear error message.

**Comment by cfpwastaken** [comment]
Ok let me pull the code up real quick

**Comment by cfpwastaken** [comment]
It should be working now? You should test it with snap tho because i cant test that sadly

**Comment by cfpwastaken** [comment]
so.. any updates?

**Comment by artivis** [comment]
The feature is now available on the `master` branch.
Closing this.

**Pull request closed without merging**
